### ISSUE TITLE
给大佬推荐一个需求

### ISSUE THREAD

**Issue by walnutYa** [jimoos-cn/jimoos-shop-portal#5]
http://182.254.189.249:7101
账号：guest/123456

可以参考下这个，加点儿tab标签的的功能

![image](https://user-images.githubusercontent.com/33886874/134446713-6a899762-96da-468e-9b21-938c997e6903.png)

**Comment by keepcleargas** [comment]
会 遇到页面缓存的问题，故去掉了。
